apiVersion: apps/v1
kind: Deployment
metadata:
  name: britive-broker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: britive-broker
  template:
    metadata:
      labels:
        app: britive-broker
    spec:
      serviceAccountName: britive-broker-sa
      containers:
        - name: britive-broker
          image: your-docker-repo/britive-broker:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: broker-config
