apiVersion: v1
kind: ServiceAccount
metadata:
  name: britive-broker-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-manager-cluster-role
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: britive-broker-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: britive-broker-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: role-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io
