[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:britive-broker]
command=/root/start-broker.sh 5
stdout_logfile=/var/log/supervisor/broker.log
stderr_logfile=/var/log/supervisor/broker.log
autostart=true
autorestart=true
environment=BRITIVE_TOKEN="%(ENV_BRITIVE_TOKEN)s"
stopasgroup=true
