AWSTemplateFormatVersion: 2010-09-09
Description: StackSet template to deploy Britive integration resources across multiple AWS accounts in an organization or folder. This template creates the SAML provider and integration role needed for Britive AWS integration.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Britive Configuration
        Parameters:
          - TenantName
          - SamlMetadataDocumentXmlContent
          - DeployAwsInvalidationFeature
    ParameterLabels:
      SamlMetadataDocumentXmlContent:
        default: SAML Metadata Document XML
      TenantName:
        default: Britive Tenant Name
      DeployAwsInvalidationFeature:
        default: Enable AWS Invalidation Feature
Parameters:
  SamlMetadataDocumentXmlContent:
    Description: The XML content of the SAML metadata document downloaded from the Britive tenant.
    Type: String
  TenantName:
    Description: Name of the Britive tenant. Omit ".britive-app.com".
    Type: String
  DeployAwsInvalidationFeature:
    Description: A flag used to indicate whether additional IAM permissions should be added to the integration role in support of the Britive AWS Invalidation feature.
    Type: String
    AllowedValues:
      - true
      - false
    Default: true
Conditions:
  ShouldDeployAwsInvalidationFeature: !Equals [!Ref DeployAwsInvalidationFeature, true]
Resources:
  BritiveSamlProvider:
    Type: AWS::IAM::SAMLProvider
    Properties:
      Name: !Sub 'britive-${TenantName}'
      SamlMetadataDocument: !Ref SamlMetadataDocumentXmlContent
  BritiveIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRoleWithSAML
              - sts:SetSourceIdentity
              - sts:TagSession
            Principal:
              Federated: !Ref BritiveSamlProvider
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      Description: !Sub 'Britive Integration Role'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
      MaxSessionDuration: 3600
      RoleName: !Sub 'britive-${TenantName}-integration-role'
  BritiveIntegrationRoleInlinePolicyForAwsInvalidation:
    Type: AWS::IAM::Policy
    Condition: ShouldDeployAwsInvalidationFeature
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:CreatePolicyVersion
              - iam:DeletePolicyVersion
              - iam:GetPolicy
              - iam:GetPolicyVersion
              - iam:ListPolicyVersions
            Resource: arn:aws:iam::*:policy/britive/managed/*
      PolicyName: aws-invalidation
      Roles:
        - !Ref BritiveIntegrationRole
Outputs:
  BritiveSamlProviderArn:
    Description: ARN of the Britive SAML Provider
    Value: !Ref BritiveSamlProvider
  BritiveIntegrationRoleArn:
    Description: ARN of the Britive Integration Role
    Value: !GetAtt BritiveIntegrationRole.Arn
  BritiveIntegrationRoleName:
    Description: Name of the Britive Integration Role
    Value: !Ref BritiveIntegrationRole
